# Generated by Django 5.0.7 on 2024-08-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpfCnpj', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=250)),
                ('quantEst', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantUsa', models.FloatField()),
                ('codMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.material')),
                ('codProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
            options={
                'unique_together': {('codProduto', 'codMaterial')},
            },
        ),
    ]
