# Generated by Django 5.0.6 on 2024-08-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produto_materialproduto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialproduto',
            unique_together={('codProduto', 'codMaterial')},
        ),
    ]
