# Generated by Django 5.0.6 on 2024-08-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_materialproduto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.FloatField(),
        ),
    ]
