# Generated by Django 5.0.6 on 2024-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=250)),
            ],
        ),
    ]
